os: linux
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - TASK=flake8
  - BACKEND=base
  - BACKEND=cryptography
  - BACKEND=pycryptodome
  - BACKEND='cryptography pycryptodome'
install:
  - pip --version
  - pip install -r requirements.txt flake8 codecov pytest-cov pytest-runner
script:
  - |
    if [[ "$TASK" == "flake8" ]]; then
      flake8 jose setup.py
    fi
  - |
    if [[ -n "$BACKEND" ]]; then
      pip install $BACKEND
    fi
  - |
    if [[ "$BACKEND" == "cryptography" ]]; then
      pip uninstall --yes ecdsa rsa
    fi

  - |
    if [[ "$BACKEND" == "pycryptodome" ]]; then
      pip uninstall --yes rsa
    fi

  - |
    if [[ -z "$TASK" ]]; then
      py.test --cov-report term-missing --cov jose tests
    fi
after_success:
  - codecov
jobs:
  exclude:
    - python: "3.7"
      env: TASK=flake8
    - python: "3.8"
      env: TASK=flake8
    - python: "pypy3"
      env: TASK=flake8
